const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate's resume and self-description match the job description."),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be asked in the interview."),
        intention: z.string().describe("The intention of interviewer behind the technical question."),
        answer: z.string().describe("Actionable coaching guidance on what to say, written as direct imperative instructions (e.g. 'Explain the phases of the event loop... Mention the role of the Libuv library... Discuss the difference between microtasks and macrotasks...'). Do NOT start with phrases like 'The candidate should' or 'The candidate should explain' — begin directly with an imperative verb such as Explain, Discuss, Mention, or Highlight."
)
    })).describe("Technical questions that can be asked in the interview, along with their intention and answer."),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question can be asked in the interview."),
        intention: z.string().describe("The intention of interviewer behind the behavioral question."),
        answer: z.string().describe("Actionable coaching guidance on how to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behavioral questions that can be asked in the interview, along with their intention and answer."),
    skillGaps: z.array(z.object({   
        skill: z.string().describe("The skill that the candidate is lacking or needs improvement."),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap, indicating how critical it is for the candidate to improve this skill.")
    })).describe("Skill gaps that the candidate has, along with their severity."),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan, starting from 1."),
        focus: z.string().describe("The main focus or topic to be covered on this day, eg. Data Structures, System Design, etc."),
        tasks: z.array(z.string()).describe("A list of tasks or activities to be completed on this day to prepare for the interview, eg. solving problems, reading articles, watching videos, etc.")
    })).describe("A day-wise preparation plan for the candidate, outlining what to focus on and what tasks to complete each day."),
    title: z.string().describe("A title of the job for which the interview report is generated."),
})

async function generateInterviewReport({
    resume = "",
    selfDescription = "",
    jobDescription = ""
} = {}) {

    const prompt = `Generate an interview report for a candidate based on the following information:
        Resume: ${resume}
        Self Description: ${selfDescription}
        Job Description: ${jobDescription}`

    const schema = z.toJSONSchema(interviewReportSchema)

    const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: schema
        }
    })

    // const report = interviewReportSchema.parse(JSON.parse(response.text))
    // console.log(JSON.stringify(report, null, 2))
    // return report

    return JSON.parse(response.text)
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: z.toJSONSchema(resumePdfSchema),
        }
    })

    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

async function generatePdfFromHtml(html) {
    const browser = await puppeteer.launch({
        args: ["--no-sandbox", "--disable-setuid-sandbox"]
    })
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: "networkidle0" })
    const pdfBuffer = await page.pdf({ format: "A4", printBackground: true })
    await browser.close()
    return pdfBuffer
}

module.exports = {
    generateInterviewReport,
    generateResumePdf,
    generatePdfFromHtml
};

